const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const st={mode:'image',img:null,name:'Sample landscape',passes:[],timer:0};
const n=(id,d=0)=>{const e=$(id),v=e?+e.value:NaN;return Number.isFinite(v)?v:d},c=id=>!!$(id)?.checked,cl=(v,a,b)=>Math.max(a,Math.min(b,v));
const len=p=>p.slice(1).reduce((s,q,i)=>s+Math.hypot(q.x-p[i].x,q.y-p[i].y),0);
function sample(){const x=document.createElement('canvas');x.width=600;x.height=400;const g=x.getContext('2d'),q=g.createLinearGradient(0,0,0,400);q.addColorStop(0,'#f1d796');q.addColorStop(.5,'#8ab7b8');q.addColorStop(1,'#233b31');g.fillStyle=q;g.fillRect(0,0,600,400);g.fillStyle='#f1cf4d';g.beginPath();g.arc(460,85,42,0,7);g.fill();g.fillStyle='#607667';g.beginPath();g.moveTo(0,330);g.lineTo(120,140);g.lineTo(230,315);g.lineTo(350,110);g.lineTo(490,320);g.lineTo(600,190);g.lineTo(600,400);g.lineTo(0,400);g.fill();g.fillStyle='#294137';g.beginPath();g.moveTo(0,350);g.quadraticCurveTo(150,270,300,350);g.quadraticCurveTo(460,275,600,345);g.lineTo(600,400);g.lineTo(0,400);g.fill();return x}
function status(t){if($('statusText'))$('statusText').textContent=t}
function raster(){const s=st.img||sample(),sw=s.naturalWidth||s.width,sh=s.naturalHeight||s.height,m=cl(n('resolution',380),80,720),r=Math.min(1,m/Math.max(sw,sh)),x=document.createElement('canvas');x.width=Math.max(2,sw*r);x.height=Math.max(2,sh*r);const g=x.getContext('2d',{willReadFrequently:true});g.filter=`blur(${n('blur',1)}px) contrast(${n('contrast',1.2)})`;g.drawImage(s,0,0,x.width,x.height);const d=g.getImageData(0,0,x.width,x.height).data,l=new Float32Array(x.width*x.height);for(let p=0;p<l.length;p++){const i=p*4,v=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];l[p]=c('invert')?255-v:v}return{w:x.width,h:x.height,l}}
function at(r,x,y){x=cl(Math.round(x),0,r.w-1);y=cl(Math.round(y),0,r.h-1);return r.l[y*r.w+x]}
function hatch(r,cross=false){const out=[],sp=Math.max(1.2,n('spacing',4.5)*r.w/Math.max(40,n('pageWidth',297))),as=cross?[n('angle',-32),n('angle',-32)+90]:[n('angle',-32)],cx=r.w/2,cy=r.h/2,D=Math.hypot(r.w,r.h),th=n('threshold',118);for(const a of as){const z=a*Math.PI/180,co=Math.cos(z),si=Math.sin(z);for(let o=-D;o<D;o+=sp){let q=[];for(let t=-D;t<D;t+=1.8){const x=cx+t*co-o*si,y=cy+t*si+o*co,on=x>=0&&y>=0&&x<r.w&&y<r.h&&at(r,x,y)<th;if(on)q.push({x,y});else{if(q.length>2)out.push([q[0],q.at(-1)]);q=[]}}}}return out}
function rows(r,edge=false){const out=[],th=edge?n('edgeThreshold',54):n('threshold',118);for(let y=2;y<r.h-2;y+=2){let q=[];for(let x=2;x<r.w-2;x+=2){let on;if(edge)on=Math.hypot(at(r,x+1,y)-at(r,x-1,y),at(r,x,y+1)-at(r,x,y-1))>th;else on=at(r,x,y)<th&&[at(r,x-2,y),at(r,x+2,y),at(r,x,y-2),at(r,x,y+2)].some(v=>v>=th);if(on)q.push({x,y});else{if(q.length>1)out.push(q);q=[]}}if(q.length>1)out.push(q)}return out}
function scan(r){const out=[],sp=Math.max(2,Math.round(n('spacing',4.5)*r.h/Math.max(40,n('pageHeight',210)))),amp=n('scanAmplitude',7)*r.h/Math.max(40,n('pageHeight',210));for(let y=sp;y<r.h;y+=sp){const p=[];for(let x=0;x<r.w;x+=2)p.push({x,y:y-(255-at(r,x,y))/255*amp});out.push(p)}return out}
function dots(r){const out=[],sp=Math.max(3,Math.round(n('spacing',4.5)*r.w/Math.max(50,n('pageWidth',297)))),rad=Math.max(.6,n('dotSize',.75)*r.w/Math.max(50,n('pageWidth',297)));let seed=(n('imageSeed',3917)|0)>>>0;const rnd=()=>((seed=Math.imul(seed^seed>>>15,1|seed)+0x6d2b79f5|0)>>>0)/4294967296;for(let y=sp;y<r.h-sp;y+=sp)for(let x=sp;x<r.w-sp;x+=sp)if(rnd()<(255-at(r,x,y))/255){const p=[];for(let i=0;i<=8;i++){const a=i/8*Math.PI*2;p.push({x:x+Math.cos(a)*rad,y:y+Math.sin(a)*rad})}out.push(p)}return out}
function transform(paths,r){const w=n('pageWidth',297),h=n('pageHeight',210),m=n('pageMargin',12),fit=Math.min((w-2*m)/r.w,(h-2*m)/r.h)*n('scalePercent',92)/100,a=n('rotation',0)*Math.PI/180,co=Math.cos(a),si=Math.sin(a),cx=r.w/2,cy=r.h/2,tx=w/2+n('offsetX'),ty=h/2+n('offsetY'),min=n('minimumPath',3);return paths.map(p=>p.map(v=>{const x=v.x-cx,y=v.y-cy;return{x:tx+(x*co-y*si)*fit,y:ty+(x*si+y*co)*fit}})).filter(p=>p.length>1&&len(p)>=min)}
function imageDoc(){const r=raster(),a=$('algorithm').value;let p=a==='crosshatch'?hatch(r,true):a==='contour'?rows(r):a==='edge'?rows(r,true):a==='scanline'?scan(r):a==='stipple'?dots(r):hatch(r);p=transform(p,r);st.passes=[{name:'Pass 1',colour:'#181a15',paths:p}]}
function patternDoc(){const w=n('pageWidth',297),h=n('pageHeight',210),m=n('pageMargin',12),k=$('patternKind').value,N=cl(Math.round(n('lineCount',42)),2,180),amp=n('amplitude',16),f=n('frequency',3.2),out=[];if(k==='spiral'){for(let j=0;j<Math.max(1,N/12);j++){const p=[];for(let i=0;i<=700;i++){const t=i/700*Math.PI*2*n('turns',9),r=(Math.min(w,h)/2-m)*i/700;p.push({x:w/2+Math.cos(t+j*.3)*r,y:h/2+Math.sin(t+j*.3)*r})}out.push(p)}}else if(k==='topographic'){for(let j=1;j<=N;j++){const p=[];for(let i=0;i<=180;i++){const t=i/180*Math.PI*2,r=(Math.min(w,h)/2-m)*j/N+Math.sin(t*f+j)*amp*.18;p.push({x:w/2+Math.cos(t)*r,y:h/2+Math.sin(t)*r})}out.push(p)}}else{for(let j=0;j<N;j++){const p=[],y0=m+j*(h-2*m)/(N-1);for(let x=m;x<=w-m;x+=1.4)p.push({x,y:y0+Math.sin(x/w*f*Math.PI*2+j*.2)*amp});out.push(p)}}st.passes=[{name:k,colour:$('patternColor').value,paths:out}];st.name=`${k} ${n('patternSeed',4281)}`}
function d(p){return p.map((v,i)=>(i?'L':'M')+v.x.toFixed(2)+' '+v.y.toFixed(2)).join(' ')}
function stats(){let draw=0,travel=0,paths=0,points=0,last=null;for(const pass of st.passes)for(const p of pass.paths){paths++;points+=p.length;draw+=len(p);if(last)travel+=Math.hypot(last.x-p[0].x,last.y-p[0].y);last=p.at(-1)}return{draw,travel,paths,points}}
function render(){const s=$('previewSvg'),w=n('pageWidth',297),h=n('pageHeight',210),m=n('pageMargin',12);s.setAttribute('viewBox',`0 0 ${w} ${h}`);s.innerHTML=`<rect width="${w}" height="${h}" fill="#f3efe3" stroke="#827b6d" stroke-width=".35"/><rect x="${m}" y="${m}" width="${Math.max(0,w-2*m)}" height="${Math.max(0,h-2*m)}" fill="none" stroke="#31382f" stroke-width=".3" stroke-dasharray="3 2"/>`;for(const pass of st.passes)for(const p of pass.paths){const q=document.createElementNS(NS,'path');q.setAttribute('d',d(p));q.setAttribute('fill','none');q.setAttribute('stroke',pass.colour);q.setAttribute('stroke-width',n('strokeWidth',.28));q.setAttribute('stroke-linecap','round');s.append(q)}const z=stats();$('documentName').textContent=st.name;$('pipelineLabel').textContent=st.mode==='pattern'?'Pattern Lab':'Image trace';$('passStat').textContent=st.passes.length;$('drawStat').textContent=(z.draw/1000).toFixed(2)+' m';$('travelStat').textContent=(z.travel/1000).toFixed(2)+' m';$('timeStat').textContent=((z.draw/n('drawFeed',1800)*60+z.travel/n('travelFeed',4200)*60)/60).toFixed(1)+' min';$('statPills').innerHTML=`<span>${z.paths} paths</span><span>${z.points} points</span>`;$('emptyState').classList.toggle('hidden',z.paths>0);$('passList').innerHTML=`<div class="pass-row"><input type="color" value="${st.passes[0]?.colour||'#181a15'}"><span>${z.paths} paths</span></div>`;$('exportPass').innerHTML='<option value="all">All enabled passes</option>';gcode()}
function gcode(){const out=['; PlotGenerator',$('startCommands').value];for(const pass of st.passes){out.push('; '+pass.name);for(const p of pass.paths){if(p.length<2)continue;out.push($('penUp').value,`G0 F${n('travelFeed',4200)} X${p[0].x.toFixed(3)} Y${p[0].y.toFixed(3)}`,$('penDown').value,`G1 F${n('drawFeed',1800)}`);for(let i=1;i<p.length;i++)out.push(`G1 X${p[i].x.toFixed(3)} Y${p[i].y.toFixed(3)}`)}}out.push($('penUp').value,$('endCommands').value);const t=out.join('\n');$('gcodePreview').value=out.slice(0,220).join('\n')+(out.length>220?'\n; … preview truncated …':'');$('gcodeMeta').textContent=`${out.length} lines`;return t}
function svg(){return`<svg xmlns="http://www.w3.org/2000/svg" width="${n('pageWidth',297)}mm" height="${n('pageHeight',210)}mm" viewBox="0 0 ${n('pageWidth',297)} ${n('pageHeight',210)}">${st.passes.map(x=>`<g fill="none" stroke="${x.colour}" stroke-width="${n('strokeWidth',.28)}">${x.paths.map(p=>`<path d="${d(p)}"/>`).join('')}</g>`).join('')}</svg>`}
function dl(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function process(){status('Generating paths');try{st.mode==='pattern'?patternDoc():imageDoc();render();status('Ready')}catch(e){console.error(e);status('Processing failed');$('warningPanel').textContent=e.message;$('warningPanel').classList.remove('hidden')}}
function schedule(ms=120){clearTimeout(st.timer);st.timer=setTimeout(process,ms)}
function mode(x){st.mode=x==='pattern'?'pattern':'image';document.querySelectorAll('[data-tab]').forEach(b=>{const a=b.dataset.tab===x;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});$('imagePanel').classList.toggle('hidden',x!=='image');$('patternPanel').classList.toggle('hidden',x!=='pattern');$('machinePanel').classList.toggle('hidden',x!=='machine');if(x!=='machine')schedule(0)}
document.addEventListener('DOMContentLoaded',()=>{st.img=sample();document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>mode(b.dataset.tab));$('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f),im=new Image();im.onload=()=>{st.img=im;st.name=f.name;$('fileName').textContent=f.name;schedule(0)};im.src=u};$('loadSample').onclick=()=>{st.img=sample();st.name='Sample landscape';schedule(0)};$('randomPatternSeed').onclick=()=>{$('patternSeed').value=Math.floor(Math.random()*1e6);schedule(0)};$('pagePreset').onchange=e=>{const d={'a4-landscape':[297,210],'a4-portrait':[210,297],'a3-landscape':[420,297],'a3-portrait':[297,420],'letter-landscape':[279,216]}[e.target.value];if(d){$('pageWidth').value=d[0];$('pageHeight').value=d[1];schedule(0)}};document.querySelectorAll('input,select,textarea').forEach(e=>{if(['fileInput','pagePreset'].includes(e.id))return;e.addEventListener(e.tagName==='TEXTAREA'?'input':'change',()=>e.closest('#machinePanel')?gcode():schedule())});$('downloadSvg').onclick=()=>dl('plot.svg',svg(),'image/svg+xml');$('downloadGcode').onclick=()=>dl('plot.gcode',gcode(),'text/plain');$('copyGcode').onclick=()=>navigator.clipboard.writeText(gcode());mode('image')});